import './globals.css'
import type { Metadata } from 'next'
import { Epilogue } from 'next/font/google'

const epilogue = Epilogue({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={epilogue.className}>
        <main className="p-5 w-[650px]">
          <div className="header mb-4">
            <p className="text-3xl text-black-400 font-medium">
              Sistem Restoran
            </p>
            <p className="text-sm text-gray-500">
              Ambisius Lab Challange 
            </p>
          </div>
          {children}
        </main>
      </body>
    </html>
  )
}
